# Generated by Django 4.2.11 on 2024-07-12 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0001_initial'),
        ('dana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penerimaan_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('penerimaan_tgl', models.DateField(verbose_name='Tanggal')),
                ('penerimaan_ket', models.CharField(max_length=200, verbose_name='Keterangan')),
                ('penerimaan_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai Uang')),
                ('penerimaan_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subrinc', verbose_name='Dana')),
                ('penerimaan_tahap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.tahapdana', verbose_name='Tahap')),
            ],
        ),
        migrations.CreateModel(
            name='DistribusiPenerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distri_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai Distribusi')),
                ('distri_ket', models.CharField(max_length=50, verbose_name='Keterangan Distribusi')),
                ('distri_penerimaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penerimaan.penerimaan', verbose_name='Penerimaan')),
                ('distri_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='OPD Penerima')),
            ],
        ),
        migrations.AddConstraint(
            model_name='penerimaan',
            constraint=models.UniqueConstraint(fields=('penerimaan_tahun', 'penerimaan_dana', 'penerimaan_tahap'), name='unique_penerimaan'),
        ),
        migrations.AddConstraint(
            model_name='distribusipenerimaan',
            constraint=models.UniqueConstraint(fields=('distri_penerimaan', 'distri_subopd'), name='unique_distrib'),
        ),
    ]
