# Generated by Django 4.2.11 on 2024-06-12 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dana', '0007_alter_dana_dana_nama_alter_kegiatan_kegiatan_dana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penerimaan_tgl', models.DateField(verbose_name='Tanggal')),
                ('penerimaan_ket', models.CharField(max_length=200, verbose_name='Keterangan')),
                ('penerimaan_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nilai Uang')),
                ('penerimaan_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subrinc', verbose_name='Dana')),
                ('penerimaan_tahap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.tahapdana', verbose_name='Tahap')),
            ],
        ),
    ]
