# Generated by Django 4.2.11 on 2024-06-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penerimaan', '0002_alter_penerimaan_penerimaan_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='penerimaan',
            name='penerimaan_tahun',
            field=models.IntegerField(default=2024, verbose_name='Tahun'),
        ),
    ]
