# Generated by Django 4.2.11 on 2024-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penerimaan', '0003_penerimaan_penerimaan_tahun'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='penerimaan',
            constraint=models.UniqueConstraint(fields=('penerimaan_tahun', 'penerimaan_dana', 'penerimaan_tahap'), name='unique_penerimaan'),
        ),
    ]
