# Generated by Django 4.2.11 on 2026-01-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penerimaan', '0003_alter_penerimaan_penerimaan_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penerimaan',
            name='penerimaan_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
    ]
