# Generated by Django 4.2.11 on 2024-07-06 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0008_alter_subopd_sub_opd'),
        ('penerimaan', '0004_penerimaan_unique_penerimaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribusiPenerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distri_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai Distribusi')),
                ('distri_ket', models.CharField(max_length=50, verbose_name='Keterangan Distribusi')),
                ('distri_penerimaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penerimaan.penerimaan', verbose_name='Penerimaan')),
                ('distri_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='OPD Penerima')),
            ],
        ),
        migrations.AddConstraint(
            model_name='distribusipenerimaan',
            constraint=models.UniqueConstraint(fields=('distri_penerimaan', 'distri_subopd'), name='unique_distrib'),
        ),
    ]
