# Generated by Django 4.2.11 on 2024-06-13 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0006_alter_opd_kode_opd_alter_opd_nama_opd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rencana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rencana_opd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.opd', verbose_name='Opd')),
            ],
        ),
    ]
