# Generated by Django 4.2.11 on 2024-06-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rencana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencana',
            name='rencana_tahun',
            field=models.IntegerField(default=2024, verbose_name='Tahun'),
        ),
    ]
