# Generated by Django 4.2.11 on 2024-06-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rencana', '0003_rencdankel_rencdankelsisa_delete_rencana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_opd',
        ),
        migrations.RemoveField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_sub',
        ),
        migrations.DeleteModel(
            name='RencDankel',
        ),
        migrations.DeleteModel(
            name='RencDankelsisa',
        ),
    ]
