# Generated by Django 6.0.1 on 2026-02-09 09:55

import django.core.validators
import djpk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Djpk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField()),
                ('jenis_dana', models.CharField(max_length=100)),
                ('file', models.FileField(help_text='Upload file PDF', upload_to=djpk.models.upload_djpk_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DJPk',
                'verbose_name_plural': 'DJPk',
                'ordering': ['-tahun', 'jenis_dana'],
            },
        ),
    ]
