# Generated by Django 6.0.1 on 2026-02-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djpk',
            name='tahap',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
