# Generated by Django 6.0.1 on 2026-02-12 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0005_alter_kegiatan_kegiatan_slug_and_more'),
        ('djpk', '0002_djpk_tahap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djpk',
            name='jenis_dana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Jenis Dana'),
        ),
        migrations.AlterField(
            model_name='djpk',
            name='tahap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.tahapdana', verbose_name='Tahap Dana'),
        ),
    ]
