# Generated by Django 6.0.1 on 2026-02-12 12:36

import django.core.validators
import djpk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpk', '0003_alter_djpk_jenis_dana_alter_djpk_tahap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djpk',
            name='file',
            field=models.FileField(error_messages={'invalid_extension': 'Hanya file PDF yang diizinkan.'}, help_text='Upload file PDF', upload_to=djpk.models.upload_djpk_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
