# Generated by Django 6.0.1 on 2026-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0005_alter_kegiatan_kegiatan_slug_and_more'),
        ('djpk', '0004_alter_djpk_file'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='djpk',
            constraint=models.UniqueConstraint(fields=('tahun', 'jenis_dana', 'tahap'), name='unique_djpk_per_tahun_dana_tahap'),
        ),
    ]
