services:

  web:
    image: tkdd:latest
    container_name: tkdd
    build: .
    env_file:
      - .env

    command: >
      /bin/bash -c "
      gunicorn project.wsgi:application
      --bind 0.0.0.0:80"

    volumes:
      - .:/project_1
      - static_volume:/project_1/staticfiles
      - media_volume:/project_1/media

    expose:
      - "80"

    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      - production_network

  celery:
    build: .
    container_name: project_celery

    command: celery -A project worker --loglevel=info

    env_file:
      - .env

    volumes:
      - media_volume:/project_1/media

    restart: always

    networks:
      - production_network

  flower:
    build:
      context: .
      dockerfile: Dockerfile-flower

    container_name: project_flower

    ports:
      - "5555:5555"

    volumes:
      - media_volume:/project_1/media

    restart: always

    networks:
      - production_network

networks:
  production_network:
    external: true

volumes:
  static_volume:
  media_volume: