# Generated by Django 4.2.11 on 2024-09-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dana', '0005_alter_kegiatan_kegiatan_slug_and_more'),
        ('opd', '0009_alter_pejabat_pejabat_foto'),
        ('dausg', '0006_alter_dankelsub_dankelsub_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rencanakesehatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rencana_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('rencana_pagu', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Kegiatan DAU SG')),
                ('rencana_output', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Output')),
                ('rencana_ket', models.TextField(max_length=17, verbose_name='Kode Sub Kegiatan DPA *) contoh :  1.01.01.2.01.0001 ')),
                ('rencana_pagudpa', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai Pagu Sub Kegiatan sesuai DPA')),
                ('rencana_verif', models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui')], default=0, editable=False)),
                ('rencana_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Sumber Dana')),
                ('rencana_kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dausg.dausgkesehatansub', verbose_name='Sub Kegiatan DAU SG')),
                ('rencana_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rencanakesehatan',
            constraint=models.UniqueConstraint(fields=('rencana_tahun', 'rencana_subopd', 'rencana_kegiatan'), name='unique_rencana_kesehatan'),
        ),
    ]
