# Generated by Django 4.2.11 on 2024-11-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesehatan', '0002_rencanakesehatanposting_realisasikesehatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasikesehatan',
            name='realisasi_output',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Capaian Output'),
        ),
    ]
