# Generated by Django 4.2.11 on 2024-11-08 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kesehatan', '0005_alter_rencanakesehatansisa_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rencanakesehatansisa',
            table=None,
        ),
    ]
