# Generated by Django 4.2.11 on 2024-11-08 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kesehatan', '0006_alter_rencanakesehatansisa_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rencanakesehatansisa',
        ),
    ]
