# Generated by Django 4.2.11 on 2025-01-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesehatan', '0009_alter_realisasikesehatan_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasikesehatan',
            name='realisasi_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='realisasikesehatansisa',
            name='realisasi_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanakesehatan',
            name='rencana_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanakesehatanposting',
            name='posting_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanakesehatanpostingsisa',
            name='posting_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanakesehatansisa',
            name='rencana_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
    ]
