# Generated by Django 4.2.11 on 2025-02-05 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0001_initial'),
        ('kesehatan', '0010_alter_realisasikesehatan_realisasi_tahun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanakesehatanposting',
            name='posting_jadwal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jadwal.jadwal', verbose_name='Posting Jadwal'),
        ),
        migrations.AlterField(
            model_name='rencanakesehatanpostingsisa',
            name='posting_jadwal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jadwal.jadwal', verbose_name='Posting Jadwal'),
        ),
    ]
