# Generated by Django 4.2.11 on 2026-01-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesehatan', '0011_alter_rencanakesehatanposting_posting_jadwal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasikesehatan',
            name='realisasi_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='realisasikesehatansisa',
            name='realisasi_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanakesehatan',
            name='rencana_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanakesehatanposting',
            name='posting_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanakesehatanpostingsisa',
            name='posting_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanakesehatansisa',
            name='rencana_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
    ]
