# Generated by Django 6.0.1 on 2026-02-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesehatan', '0012_alter_realisasikesehatan_realisasi_tahun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasikesehatan',
            name='realisasi_sp2d',
            field=models.CharField(max_length=100, verbose_name='No SP2D'),
        ),
        migrations.AlterField(
            model_name='realisasikesehatansisa',
            name='realisasi_sp2d',
            field=models.CharField(max_length=100, verbose_name='No SP2D'),
        ),
    ]
