# Generated by Django 4.2.11 on 2024-07-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dana_nama', models.CharField(max_length=30, verbose_name='Dana')),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegiatan_nama', models.CharField(max_length=200, verbose_name='Kegiatan')),
                ('kegiatan_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana', verbose_name='Dana')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_nama', models.CharField(max_length=200, verbose_name='Program')),
                ('program_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana', verbose_name='Dana')),
            ],
        ),
        migrations.CreateModel(
            name='Subkegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_nama', models.CharField(max_length=200, verbose_name='Sub Kegiatan')),
                ('sub_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana', verbose_name='Dana')),
                ('sub_keg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.kegiatan', verbose_name='Kegiatan')),
                ('sub_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.program', verbose_name='Program')),
            ],
        ),
        migrations.CreateModel(
            name='TahapDana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahap_dana', models.CharField(max_length=50, verbose_name='Dana')),
            ],
        ),
        migrations.CreateModel(
            name='Subrinc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subrinc_nama', models.CharField(max_length=200, verbose_name='Rincian Sub Kegiatan')),
                ('subrinc_slug', models.SlugField(allow_unicode=True, editable=False, unique=True)),
                ('subrinc_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana', verbose_name='Dana')),
                ('subrinc_keg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.kegiatan', verbose_name='Kegiatan')),
                ('subrinc_kegsub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Sub Kegiatan')),
                ('subrinc_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.program', verbose_name='Program')),
            ],
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='kegiatan_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.program', verbose_name='Program'),
        ),
    ]
