# Generated by Django 4.2.11 on 2024-07-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='kegiatan_slug',
            field=models.SlugField(allow_unicode=True, default='dana', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
