# Generated by Django 4.2.11 on 2024-05-30 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegiatan_nama', models.CharField(max_length=200)),
                ('kegiatan_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_nama', models.CharField(max_length=50)),
                ('program_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana')),
            ],
        ),
        migrations.CreateModel(
            name='Subkegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_nama', models.CharField(max_length=200)),
                ('sub_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana')),
                ('sub_keg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.kegiatan')),
                ('sub_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.program')),
            ],
        ),
        migrations.CreateModel(
            name='TahapDana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahap_dana', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubRincian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subrinc_nama', models.CharField(max_length=200)),
                ('subrinc_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana')),
                ('subrinc_keg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.kegiatan')),
                ('subrinc_kegsub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan')),
                ('subrinc_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.program')),
            ],
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='kegiatan_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.program'),
        ),
    ]
