# Generated by Django 4.2.11 on 2024-07-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0002_kegiatan_kegiatan_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegiatan',
            name='kegiatan_dana',
        ),
    ]
