# Generated by Django 4.2.11 on 2024-05-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0002_kegiatan_program_subkegiatan_tahapdana_subrincian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_nama',
            field=models.CharField(max_length=200),
        ),
    ]
