# Generated by Django 4.2.11 on 2024-05-30 13:10

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0003_alter_program_program_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='kegiatan_program',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='kegiatan_dana', chained_model_field='program_dana', on_delete=django.db.models.deletion.CASCADE, to='dana.program'),
        ),
    ]
