# Generated by Django 4.2.11 on 2024-07-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0003_remove_kegiatan_kegiatan_dana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subkegiatan',
            name='sub_dana',
        ),
        migrations.RemoveField(
            model_name='subkegiatan',
            name='sub_prog',
        ),
        migrations.AddField(
            model_name='subkegiatan',
            name='sub_slug',
            field=models.SlugField(allow_unicode=True, default='dana', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
