# Generated by Django 4.2.11 on 2024-09-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0004_remove_subkegiatan_sub_dana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='kegiatan_slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subkegiatan',
            name='sub_slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=200, unique=True),
        ),
    ]
