# Generated by Django 4.2.11 on 2024-05-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0004_alter_kegiatan_kegiatan_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='kegiatan_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.program'),
        ),
    ]
