# Generated by Django 4.2.11 on 2024-06-04 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0005_alter_kegiatan_kegiatan_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubRincian',
            new_name='Subrinc',
        ),
    ]
