# Generated by Django 4.2.11 on 2024-06-12 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0006_rename_subrincian_subrinc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dana',
            name='dana_nama',
            field=models.CharField(max_length=30, verbose_name='Dana'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='kegiatan_dana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana', verbose_name='Dana'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='kegiatan_nama',
            field=models.CharField(max_length=200, verbose_name='Kegiatan'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='kegiatan_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_dana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana', verbose_name='Dana'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_nama',
            field=models.CharField(max_length=200, verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='subkegiatan',
            name='sub_dana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana', verbose_name='Dana'),
        ),
        migrations.AlterField(
            model_name='subkegiatan',
            name='sub_keg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.kegiatan', verbose_name='Kegiatan'),
        ),
        migrations.AlterField(
            model_name='subkegiatan',
            name='sub_nama',
            field=models.CharField(max_length=200, verbose_name='Sub Kegiatan'),
        ),
        migrations.AlterField(
            model_name='subkegiatan',
            name='sub_prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='subrinc',
            name='subrinc_dana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana', verbose_name='Dana'),
        ),
        migrations.AlterField(
            model_name='subrinc',
            name='subrinc_keg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.kegiatan', verbose_name='Kegiatan'),
        ),
        migrations.AlterField(
            model_name='subrinc',
            name='subrinc_kegsub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Sub Kegiatan'),
        ),
        migrations.AlterField(
            model_name='subrinc',
            name='subrinc_nama',
            field=models.CharField(max_length=200, verbose_name='Rincian Sub Kegiatan'),
        ),
        migrations.AlterField(
            model_name='subrinc',
            name='subrinc_prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='tahapdana',
            name='tahap_dana',
            field=models.CharField(max_length=50, verbose_name='Dana'),
        ),
    ]
