# Generated by Django 4.2.11 on 2024-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0007_alter_dana_dana_nama_alter_kegiatan_kegiatan_dana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrinc',
            name='subrinc_slug',
            field=models.SlugField(allow_unicode=True, default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
