# Generated by Django 4.2.11 on 2024-06-05 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dana', '0006_rename_subrincian_subrinc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DankelProg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dankel_prog', models.CharField(max_length=200)),
                ('subrinc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subrinc')),
            ],
        ),
    ]
