# Generated by Django 4.2.11 on 2024-07-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0004_remove_subkegiatan_sub_dana_and_more'),
        ('dausg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dankelprog',
            name='dankel_subrinc',
        ),
        migrations.RemoveField(
            model_name='dausgkesehatanprog',
            name='dausgkesehatan_subrinc',
        ),
        migrations.RemoveField(
            model_name='dausgpendidikanprog',
            name='dausgpendidikan_subrinc',
        ),
        migrations.RemoveField(
            model_name='dausgpuprog',
            name='dausgpu_subrinc',
        ),
        migrations.AlterField(
            model_name='dankelprog',
            name='dankel_dana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Dana'),
        ),
        migrations.AlterField(
            model_name='dausgkesehatanprog',
            name='dausgkesehatan_dana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Dana'),
        ),
        migrations.AlterField(
            model_name='dausgpendidikanprog',
            name='dausgpendidikan_dana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Dana'),
        ),
        migrations.AlterField(
            model_name='dausgpuprog',
            name='dausgpu_dana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Dana'),
        ),
    ]
