# Generated by Django 4.2.11 on 2024-06-05 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0006_rename_subrincian_subrinc'),
        ('dausg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dankelprog',
            old_name='subrinc',
            new_name='dankel_subrinc',
        ),
        migrations.AddField(
            model_name='dankelprog',
            name='dankel_dana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dana.dana'),
            preserve_default=False,
        ),
    ]
