# Generated by Django 4.2.11 on 2024-06-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dausg', '0002_rename_subrinc_dankelprog_dankel_subrinc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DankelKeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dankelkeg_nama', models.CharField(max_length=200)),
                ('dankelkeg_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dausg.dankelprog')),
            ],
        ),
    ]
