# Generated by Django 4.2.11 on 2024-06-10 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dausg', '0003_dankelkeg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dankelkeg',
            name='dankelkeg_prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dankelkegs', to='dausg.dankelprog'),
        ),
    ]
