# Generated by Django 4.2.11 on 2024-08-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dausg', '0003_alter_dausgpendidikansub_dausgpendidikansub_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dausgkesehatansub',
            name='dausgkesehatansub_nama',
            field=models.CharField(max_length=500, verbose_name='Sub Kegiatan DAUSG kesehatan'),
        ),
        migrations.AlterField(
            model_name='dausgpusub',
            name='dausgpusub_nama',
            field=models.CharField(max_length=500, verbose_name='Sub Kegiatan DAUSG Pekerjaan Umum'),
        ),
    ]
