# Generated by Django 4.2.11 on 2024-06-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dausg', '0004_alter_dankelkeg_dankelkeg_prog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dankelsub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dankelsub_nama', models.CharField(max_length=200)),
                ('dankelsub_keg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dausg.dankelkeg')),
            ],
        ),
    ]
