# Generated by Django 4.2.11 on 2024-06-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dausg', '0005_dankelsub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dankelsub',
            name='dankelsub_keg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dankelsubs', to='dausg.dankelkeg'),
        ),
    ]
