# Generated by Django 4.2.11 on 2024-09-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dausg', '0005_alter_dausgkesehatankeg_dausgkesehatankeg_nama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dankelsub',
            name='dankelsub_nama',
            field=models.CharField(max_length=500, verbose_name='Sub Kegiatan Dana Kelurahan'),
        ),
    ]
