# Generated by Django 4.2.11 on 2025-01-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dausg', '0006_alter_dankelsub_dankelsub_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='dankelprog',
            name='dankel_tahun',
            field=models.IntegerField(default=2024, verbose_name='Tahun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dausgkesehatanprog',
            name='dausgkesehatan_tahun',
            field=models.IntegerField(default=2024, verbose_name='Tahun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dausgpendidikanprog',
            name='dausgpendidikan_tahun',
            field=models.IntegerField(default=2024, verbose_name='Tahun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dausgpuprog',
            name='ddausgpu_tahun',
            field=models.IntegerField(default=2024, verbose_name='Tahun'),
            preserve_default=False,
        ),
    ]
