# Generated by Django 4.2.11 on 2024-06-12 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0007_alter_dana_dana_nama_alter_kegiatan_kegiatan_dana_and_more'),
        ('dausg', '0006_alter_dankelsub_dankelsub_keg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dankelkeg',
            name='dankelkeg_nama',
            field=models.CharField(max_length=200, verbose_name='Kegiatan DAUSG'),
        ),
        migrations.AlterField(
            model_name='dankelkeg',
            name='dankelkeg_prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dankelkegs', to='dausg.dankelprog', verbose_name='Program DAUSG'),
        ),
        migrations.AlterField(
            model_name='dankelprog',
            name='dankel_dana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.dana', verbose_name='Dana'),
        ),
        migrations.AlterField(
            model_name='dankelprog',
            name='dankel_prog',
            field=models.CharField(max_length=200, verbose_name='Program DAUSG'),
        ),
        migrations.AlterField(
            model_name='dankelprog',
            name='dankel_subrinc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subrinc', verbose_name='Sub Rincian Dana'),
        ),
        migrations.AlterField(
            model_name='dankelsub',
            name='dankelsub_keg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dankelsubs', to='dausg.dankelkeg', verbose_name='Kegiatan DAUSG'),
        ),
        migrations.AlterField(
            model_name='dankelsub',
            name='dankelsub_nama',
            field=models.CharField(max_length=200, verbose_name='Sub Kegiatan DAUSG'),
        ),
    ]
