# Generated by Django 4.2.11 on 2025-01-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dausg', '0007_dankelprog_dankel_tahun_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dausgpuprog',
            old_name='ddausgpu_tahun',
            new_name='dausgpu_tahun',
        ),
    ]
