# Generated by Django 4.2.11 on 2024-06-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dausg', '0007_alter_dankelkeg_dankelkeg_nama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dankelsub',
            name='dankelsub_satuan',
            field=models.CharField(default=1, max_length=200, verbose_name='Satuan'),
            preserve_default=False,
        ),
    ]
