# Generated by Django 6.0.1 on 2026-02-13 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dausg', '0008_rename_ddausgpu_tahun_dausgpuprog_dausgpu_tahun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCopyTahun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sektor', models.CharField(max_length=50)),
                ('tahun_asal', models.IntegerField()),
                ('tahun_tujuan', models.IntegerField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Berhasil'), ('FAILED', 'Gagal')], max_length=20)),
                ('pesan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
