# Generated by Django 4.2.11 on 2024-07-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dana', '0001_initial'),
        ('opd', '0003_alter_opd_kode_opd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagudausg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagudausg_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('pagudausg_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Anggaran')),
                ('pagudausg_sisa', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Sisa Anggaran')),
                ('pagudausg_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.kegiatan', verbose_name='Dana')),
                ('pagudausg_opd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub OPD')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pagudausg',
            constraint=models.UniqueConstraint(fields=('pagudausg_tahun', 'pagudausg_opd', 'pagudausg_dana'), name='unique_pagudausg'),
        ),
    ]
