# Generated by Django 4.2.11 on 2024-06-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0008_alter_subopd_sub_opd'),
        ('dana', '0008_subrinc_subrinc_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagudausg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagudausg_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('pagudausg_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Anggaran')),
                ('pagudausg_sisa', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Sisa Anggaran')),
                ('pagudausg_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subrinc', verbose_name='Dana')),
                ('pagudausg_opd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub OPD')),
            ],
        ),
    ]
