# Generated by Django 4.2.11 on 2024-06-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagu', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pagudausg',
            constraint=models.UniqueConstraint(fields=('pagudausg_tahun', 'pagudausg_opd', 'pagudausg_dana'), name='unique_pagudausg'),
        ),
    ]
