# Generated by Django 4.2.11 on 2025-01-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagu', '0002_alter_pagudausg_pagudausg_dana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagudausg',
            name='pagudausg_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
    ]
