EXCEL_FIELD_MAPPING = {
    'Kode Sub SKPD': 'kode_sub_skpd',
    'Nama Sub SKPD': 'nama_sub_skpd',
    'Kode Program': 'kode_program',
    'Nama Program': 'nama_program',
    'Kode Kegiatan': 'kode_kegiatan',
    'Nama Kegiatan': 'nama_kegiatan',
    'Kode Sub Kegiatan': 'kode_sub_kegiatan',
    'Nama Sub Kegiatan': 'nama_sub_kegiatan',
    'Kode Rekening': 'kode_rekening',
    'Nama Rekening': 'nama_rekening',
    'Nomor Dokumen': 'nomor_dokumen',
    'Jenis Dokumen': 'jenis_dokumen',
    'Jenis Transaksi': 'jenis_transaksi',
    'Nomor DPT': 'nomor_dpt',
    'Tanggal Dokumen': 'tanggal_dokumen',
    'Keterangan Dokumen': 'keterangan_dokumen',
    'Nilai Realisasi': 'nilai_realisasi',
    'Nilai Setoran': 'nilai_setoran',
    'Nomor SPP': 'nomor_spp',
    'Tanggal SPP': 'tanggal_spp',
    'Nomor SPM': 'nomor_spm',
    'Tanggal SPM': 'tanggal_spm',
    'Nomor SP2D': 'nomor_sp2d',
    'Tanggal SP2D': 'tanggal_sp2d',
    'Tanggal Transfer': 'tanggal_transfer',
    'Nilai SP2D': 'nilai_sp2d',
}
