# Generated by Django 4.2.11 on 2024-07-25 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opd', '0003_alter_opd_kode_opd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_nama', models.CharField(error_messages={'unique': 'Maaf, data ini sudah ada dalam database.'}, max_length=30, unique=True, verbose_name='Level')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_nama', models.CharField(error_messages={'unique': 'Maaf, data ini sudah ada dalam database.'}, max_length=30, unique=True, verbose_name='Menu')),
                ('menu_icon', models.CharField(max_length=40, verbose_name='Icon')),
                ('menu_link', models.CharField(blank=True, max_length=40, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Userlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nama', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
                ('userlevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.level', verbose_name='Level')),
                ('userlevelopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlevel', to='opd.subopd', verbose_name='Sub OPD')),
            ],
        ),
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submenu_nama', models.CharField(max_length=30, verbose_name='Sub Menu')),
                ('submenu_icon', models.CharField(max_length=40, verbose_name='Icon')),
                ('submenu_link', models.CharField(blank=True, max_length=40, verbose_name='Link')),
                ('submenu_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.menu', verbose_name='Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Levelsub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lihat', models.BooleanField(default=False, verbose_name='Lihat Data')),
                ('simpan', models.BooleanField(default=False, verbose_name='Simpan Data')),
                ('edit', models.BooleanField(default=False, verbose_name='Edit Data')),
                ('hapus', models.BooleanField(default=False, verbose_name='Hapus Data')),
                ('levelsub_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.level', verbose_name='Level')),
                ('levelsub_submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.submenu', verbose_name='Level Sub Menu')),
            ],
        ),
    ]
