# Generated by Django 4.2.11 on 2024-05-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level_submenu',
        ),
        migrations.AddField(
            model_name='level',
            name='level_submenu',
            field=models.ManyToManyField(to='dashboard.submenu'),
        ),
    ]
