# Generated by Django 4.2.11 on 2024-05-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_level_level_submenu_level_level_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_icon',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_link',
            field=models.CharField(default='test', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenu',
            name='submenu_icon',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenu',
            name='submenu_link',
            field=models.CharField(default='test', max_length=25),
            preserve_default=False,
        ),
    ]
