# Generated by Django 4.2.11 on 2024-05-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_menu_menu_icon_menu_menu_link_submenu_submenu_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_icon',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='submenu_icon',
            field=models.CharField(max_length=30),
        ),
    ]
