# Generated by Django 4.2.11 on 2024-05-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_menu_menu_link_alter_submenu_submenu_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_icon',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_link',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_nama',
            field=models.CharField(error_messages={'unique': 'Maaf, nilai ini sudah ada dalam database.'}, max_length=30, unique=True),
        ),
    ]
