# Generated by Django 4.2.11 on 2024-05-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_menu_menu_icon_alter_menu_menu_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_nama',
            field=models.CharField(error_messages={'unique': 'Maaf, data ini sudah ada dalam database.'}, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='submenu_icon',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='submenu_link',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='submenu_nama',
            field=models.CharField(error_messages={'unique': 'Maaf, data ini sudah ada dalam database.'}, max_length=30, unique=True),
        ),
    ]
