# Generated by Django 4.2.11 on 2024-05-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_menu_menu_nama_alter_submenu_submenu_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level_user',
        ),
    ]
