# Generated by Django 4.2.11 on 2024-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_level_level_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_nama',
            field=models.CharField(error_messages={'unique': 'Maaf, data ini sudah ada dalam database.'}, max_length=30, unique=True),
        ),
    ]
