# Generated by Django 4.2.11 on 2024-05-30 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_alter_opd_kode_opd'),
        ('dashboard', '0013_alter_userlevel_userlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='userlevelopd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opd.opd'),
            preserve_default=False,
        ),
    ]
