# Generated by Django 4.2.11 on 2024-06-12 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0006_alter_opd_kode_opd_alter_opd_nama_opd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_userlevel_userlevelopd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_nama',
            field=models.CharField(error_messages={'unique': 'Maaf, data ini sudah ada dalam database.'}, max_length=30, unique=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_submenu',
            field=models.ManyToManyField(to='dashboard.submenu', verbose_name='Level Sub Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_icon',
            field=models.CharField(max_length=40, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_link',
            field=models.CharField(blank=True, max_length=40, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_nama',
            field=models.CharField(error_messages={'unique': 'Maaf, data ini sudah ada dalam database.'}, max_length=30, unique=True, verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='submenu_icon',
            field=models.CharField(max_length=40, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='submenu_link',
            field=models.CharField(blank=True, max_length=40, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='submenu_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.menu', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='submenu_nama',
            field=models.CharField(error_messages={'unique': 'Maaf, data ini sudah ada dalam database.'}, max_length=30, unique=True, verbose_name='Sub Menu'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='user_nama',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='userlevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.level', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='userlevelopd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.opd', verbose_name='OPD'),
        ),
    ]
