# Generated by Django 4.2.11 on 2024-06-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_level_level_nama_alter_level_level_submenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='submenu_nama',
            field=models.CharField(max_length=30, verbose_name='Sub Menu'),
        ),
    ]
