# Generated by Django 4.2.11 on 2024-06-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0008_alter_subopd_sub_opd'),
        ('dashboard', '0016_alter_submenu_submenu_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='userlevelopd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub OPD'),
        ),
    ]
