# Generated by Django 4.2.11 on 2024-06-19 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0008_alter_subopd_sub_opd'),
        ('dashboard', '0017_alter_userlevel_userlevelopd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='userlevelopd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlevel', to='opd.subopd', verbose_name='Sub OPD'),
        ),
    ]
