# Generated by Django 4.2.11 on 2024-07-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_userlevel_userlevelopd'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='lihat',
            field=models.BooleanField(default=False, verbose_name='List Data'),
        ),
        migrations.AddField(
            model_name='level',
            name='simpan',
            field=models.BooleanField(default=False, verbose_name='Simpan Data'),
        ),
    ]
