# Generated by Django 4.2.11 on 2024-07-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_level_lihat_level_simpan'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Hapus Data'),
        ),
        migrations.AddField(
            model_name='level',
            name='update',
            field=models.BooleanField(default=False, verbose_name='Update Data'),
        ),
    ]
