# Generated by Django 4.2.11 on 2024-07-11 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_level_delete_level_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='level',
            name='level_submenu',
        ),
        migrations.RemoveField(
            model_name='level',
            name='lihat',
        ),
        migrations.RemoveField(
            model_name='level',
            name='simpan',
        ),
        migrations.RemoveField(
            model_name='level',
            name='update',
        ),
        migrations.CreateModel(
            name='Levelsub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lihat', models.BooleanField(default=False, verbose_name='List Data')),
                ('simpan', models.BooleanField(default=False, verbose_name='Simpan Data')),
                ('update', models.BooleanField(default=False, verbose_name='Update Data')),
                ('delete', models.BooleanField(default=False, verbose_name='Hapus Data')),
                ('levelsub_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.level', verbose_name='Level')),
                ('levelsub_submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.submenu', verbose_name='Level Sub Menu')),
            ],
        ),
    ]
