# Generated by Django 4.2.11 on 2024-09-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0009_alter_pejabat_pejabat_foto'),
        ('dana', '0005_alter_kegiatan_kegiatan_slug_and_more'),
        ('dausg', '0006_alter_dankelsub_dankelsub_nama'),
        ('pu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realisasipekerjaanumum',
            new_name='Realisasipu',
        ),
        migrations.RenameModel(
            old_name='Rencanapekerjaanumum',
            new_name='Rencanapu',
        ),
        migrations.RenameModel(
            old_name='Rencanapekerjaanumumposting',
            new_name='Rencanapuposting',
        ),
        migrations.RemoveConstraint(
            model_name='rencanapu',
            name='unique_rencana_pekerjaanumum',
        ),
        migrations.AddConstraint(
            model_name='rencanapu',
            constraint=models.UniqueConstraint(fields=('rencana_tahun', 'rencana_subopd', 'rencana_kegiatan'), name='unique_rencana_pu'),
        ),
    ]
