# Generated by Django 4.2.11 on 2024-09-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pu', '0002_rename_realisasipekerjaanumum_realisasipu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasipu',
            name='realisasi_output',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Capaian Output'),
        ),
    ]
