# Generated by Django 4.2.11 on 2025-02-05 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0001_initial'),
        ('pu', '0005_alter_realisasipu_realisasi_tahun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanapuposting',
            name='posting_jadwal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jadwal.jadwal', verbose_name='Posting Jadwal'),
        ),
        migrations.AlterField(
            model_name='rencanapupostingsisa',
            name='posting_jadwal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jadwal.jadwal', verbose_name='Posting Jadwal'),
        ),
    ]
