# Generated by Django 6.0.1 on 2026-02-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pu', '0007_alter_realisasipu_realisasi_tahun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasipu',
            name='realisasi_sp2d',
            field=models.CharField(max_length=100, verbose_name='No SP2D'),
        ),
        migrations.AlterField(
            model_name='realisasipusisa',
            name='realisasi_sp2d',
            field=models.CharField(max_length=100, verbose_name='No SP2D'),
        ),
    ]
