# Generated by Django 4.2.11 on 2025-02-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jadwal_tahun', models.IntegerField(verbose_name='Tahun')),
                ('jadwal_keterangan', models.CharField(max_length=200, verbose_name='Keterangan')),
                ('jadwal_aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
        ),
    ]
