# Generated by Django 6.0.1 on 2026-02-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jadwal',
            index=models.Index(fields=['jadwal_tahun', 'jadwal_aktif'], name='jadwal_jadw_jadwal__9104c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='jadwal',
            constraint=models.UniqueConstraint(condition=models.Q(('jadwal_aktif', True)), fields=('jadwal_tahun',), name='unique_active_jadwal_per_tahun'),
        ),
    ]
