# Generated by Django 4.2.11 on 2026-01-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sipd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('kode_sub_skpd', models.CharField(max_length=50)),
                ('nama_sub_skpd', models.CharField(max_length=255)),
                ('kode_program', models.CharField(max_length=50)),
                ('nama_program', models.CharField(max_length=255)),
                ('kode_kegiatan', models.CharField(max_length=50)),
                ('nama_kegiatan', models.CharField(max_length=255)),
                ('kode_sub_kegiatan', models.CharField(max_length=50)),
                ('nama_sub_kegiatan', models.CharField(max_length=255)),
                ('kode_rekening', models.CharField(max_length=50)),
                ('nama_rekening', models.CharField(max_length=255)),
                ('nomor_dokumen', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_dokumen', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_transaksi', models.CharField(blank=True, max_length=50, null=True)),
                ('nomor_dpt', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_dokumen', models.DateField(blank=True, null=True)),
                ('keterangan_dokumen', models.TextField(blank=True, null=True)),
                ('nilai_realisasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('nilai_setoran', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('nomor_spp', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_spp', models.DateField(blank=True, null=True)),
                ('nomor_spm', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_spm', models.DateField(blank=True, null=True)),
                ('nomor_sp2d', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_sp2d', models.DateField(blank=True, null=True)),
                ('tanggal_transfer', models.DateField(blank=True, null=True)),
                ('nilai_sp2d', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Realisasi SIPD',
                'verbose_name_plural': 'Realisasi SIPD',
                'db_table': 'sipd',
                'unique_together': {('kode_sub_skpd', 'kode_sub_kegiatan', 'kode_rekening', 'nomor_dokumen')},
            },
        ),
    ]
