# Generated by Django 4.2.11 on 2026-01-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipd', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sipd',
            unique_together={('tahun', 'kode_sub_skpd', 'kode_sub_kegiatan', 'kode_rekening', 'nomor_dokumen')},
        ),
    ]
