# Generated by Django 6.0.1 on 2026-02-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipd', '0002_alter_sipd_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sipd',
            unique_together={('tahun', 'kode_sub_skpd', 'kode_sub_kegiatan', 'kode_rekening', 'nomor_dokumen', 'nomor_spm', 'nomor_sp2d')},
        ),
    ]
