# Generated by Django 6.0.1 on 2026-02-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipd', '0004_importlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportLog',
        ),
    ]
