# Generated by Django 6.0.1 on 2026-03-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipd', '0005_delete_importlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipd',
            name='nama_kegiatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sipd',
            name='nama_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sipd',
            name='nama_rekening',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sipd',
            name='nama_sub_kegiatan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
