# Generated by Django 6.0.1 on 2026-03-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipd', '0006_alter_sipd_nama_kegiatan_alter_sipd_nama_program_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sipd',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='sipd',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sipd',
            name='nomor_dokumen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sipd',
            name='nomor_sp2d',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sipd',
            name='nomor_spm',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='sipd',
            constraint=models.UniqueConstraint(fields=('tahun', 'kode_sub_skpd', 'kode_sub_kegiatan', 'kode_rekening', 'nomor_dokumen', 'nomor_spm', 'nomor_sp2d'), name='unique_sipd_data'),
        ),
        migrations.AddConstraint(
            model_name='sipd',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('nomor_dokumen', ''), _negated=True), models.Q(('nomor_spm', ''), _negated=True), models.Q(('nomor_sp2d', ''), _negated=True)), name='no_empty_unique_fields'),
        ),
    ]
