# Generated by Django 6.0.1 on 2026-03-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipd', '0007_alter_sipd_options_alter_sipd_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBP',
            fields=[
                ('nomor', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_tbp', models.DateField()),
                ('nomor_tbp', models.CharField(max_length=100, unique=True)),
                ('keterangan_tbp', models.TextField(blank=True, null=True)),
                ('status_tbp', models.CharField(blank=True, max_length=50, null=True)),
                ('nilai_tbp', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbp',
                'ordering': ['-tanggal_tbp'],
            },
        ),
    ]
