# Generated by Django 6.0.1 on 2026-03-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipd', '0008_tbp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbp',
            name='nomor',
        ),
        migrations.AddField(
            model_name='tbp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbp',
            name='tahun',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
    ]
