# Generated by Django 6.0.1 on 2026-03-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipd', '0009_remove_tbp_nomor_tbp_id_tbp_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbp',
            name='nomor_tbp',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbp',
            name='tanggal_tbp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tbp',
            index=models.Index(fields=['tahun'], name='tbp_tahun_edb12b_idx'),
        ),
        migrations.AddIndex(
            model_name='tbp',
            index=models.Index(fields=['nomor_tbp'], name='tbp_nomor_t_52a3e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='tbp',
            constraint=models.UniqueConstraint(fields=('tahun', 'nomor_tbp'), name='unique_tbp_per_tahun'),
        ),
    ]
