# Generated by Django 6.0.1 on 2026-03-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipd', '0010_alter_tbp_nomor_tbp_alter_tbp_tanggal_tbp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbp',
            name='status_tbp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
