# Generated by Django 4.2.11 on 2024-07-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dana', '0001_initial'),
        ('dausg', '0001_initial'),
        ('opd', '0003_alter_opd_kode_opd'),
    ]

    operations = [
        migrations.CreateModel(
            name='RencDankelsisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rencdankelsisa_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('rencdankelsisa_pagu', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Anggaran Sisa')),
                ('rencdankelsisa_output', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Output Sisa')),
                ('rencdankelsisa_ket', models.TextField(blank=True, verbose_name='Keterangan Kegiatan Sisa')),
                ('rencdankelsisa_verif', models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0, editable=False)),
                ('rencdankelsisa_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.kegiatan', verbose_name='Sumber Dana')),
                ('rencdankelsisa_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dausg.dankelsub', verbose_name='Sub Kegiatan')),
                ('rencdankelsisa_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd')),
            ],
        ),
        migrations.CreateModel(
            name='RencDankel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rencdankel_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('rencdankel_pagu', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Anggaran')),
                ('rencdankel_output', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Output')),
                ('rencdankel_ket', models.TextField(blank=True, verbose_name='Keterangan Kegiatan')),
                ('rencdankel_verif', models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0, editable=False)),
                ('rencdankel_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.kegiatan', verbose_name='Sumber Dana')),
                ('rencdankel_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dausg.dankelsub', verbose_name='Sub Kegiatan')),
                ('rencdankel_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd')),
            ],
        ),
        migrations.CreateModel(
            name='RealisasiDankel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realisasidankel_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('realisasidankel_sp2dtu', models.CharField(max_length=100, verbose_name='No SP2D TU')),
                ('realisasidankel_tgl', models.DateField(verbose_name='Tanggal SP2D TU')),
                ('realisasidankel_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai SP2D')),
                ('realisasidankel_lpj', models.CharField(max_length=100, verbose_name='No LPJ TU')),
                ('realisasidankel_lpjtgl', models.DateField(verbose_name='Tanggal LPJ TU')),
                ('realisasidankel_lpjnilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai LPJ TU')),
                ('realisasidankel_sts', models.CharField(max_length=100, verbose_name='No STS TU')),
                ('realisasidankel_ststgl', models.DateField(verbose_name='Tanggal STS TU')),
                ('realisasidankel_stsnilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai STS TU')),
                ('realisasidankel_verif', models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0, editable=False)),
                ('realisasidankel_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.kegiatan', verbose_name='Sumber Dana')),
                ('realisasidankel_rencana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dankel.rencdankel', verbose_name='Kegiatan')),
                ('realisasidankel_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd')),
                ('realisasidankel_tahap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.tahapdana', verbose_name='Tahap Realisasi')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rencdankelsisa',
            constraint=models.UniqueConstraint(fields=('rencdankelsisa_tahun', 'rencdankelsisa_subopd', 'rencdankelsisa_sub'), name='unique_rencdankelsisa'),
        ),
        migrations.AddConstraint(
            model_name='rencdankel',
            constraint=models.UniqueConstraint(fields=('rencdankel_tahun', 'rencdankel_subopd', 'rencdankel_sub'), name='unique_rencdankel'),
        ),
    ]
