# Generated by Django 4.2.11 on 2024-06-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_opd',
        ),
        migrations.RemoveField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_sub',
        ),
        migrations.RemoveField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_tahun',
        ),
        migrations.AddField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_rencana',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dankel.rencdankel', verbose_name='Rencana Kegiatan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rencdankel',
            name='rencdankel_ket',
            field=models.TextField(blank=True, verbose_name='Keterangan Kegiatan'),
        ),
        migrations.AlterField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_ket',
            field=models.TextField(blank=True, verbose_name='Keterangan Kegiatan Sisa'),
        ),
        migrations.AlterField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_output',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Output Sisa'),
        ),
        migrations.AlterField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_pagu',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Anggaran Sisa'),
        ),
    ]
