# Generated by Django 4.2.11 on 2024-07-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Realdankeldetail',
        ),
    ]
