# Generated by Django 4.2.11 on 2024-06-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0002_remove_rencdankelsisa_rencdankelsisa_opd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_rencana',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rencdankelsisa', to='dankel.rencdankel', verbose_name='Rencana Kegiatan'),
        ),
    ]
