# Generated by Django 4.2.11 on 2024-07-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0002_alter_realisasidankel_realisasidankel_dana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasidankel',
            name='realisasidankel_lpj',
            field=models.CharField(max_length=100, unique=True, verbose_name='No LPJ TU'),
        ),
        migrations.AlterField(
            model_name='realisasidankel',
            name='realisasidankel_sp2dtu',
            field=models.CharField(max_length=100, unique=True, verbose_name='No SP2D TU'),
        ),
        migrations.AlterField(
            model_name='realisasidankel',
            name='realisasidankel_sts',
            field=models.CharField(max_length=100, unique=True, verbose_name='No STS TU'),
        ),
    ]
