# Generated by Django 4.2.11 on 2024-07-31 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_alter_opd_kode_opd'),
        ('dana', '0004_remove_subkegiatan_sub_dana_and_more'),
        ('dankel', '0003_alter_realisasidankel_realisasidankel_lpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealisasiDankelsisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realisasidankelsisa_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('realisasidankelsisa_sp2dtu', models.CharField(max_length=100, unique=True, verbose_name='No SP2D TU')),
                ('realisasidankelsisa_tgl', models.DateField(verbose_name='Tanggal SP2D TU')),
                ('realisasidankelsisa_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai SP2D')),
                ('realisasidankelsisa_lpj', models.CharField(max_length=100, unique=True, verbose_name='No LPJ TU')),
                ('realisasidankelsisa_lpjtgl', models.DateField(verbose_name='Tanggal LPJ TU')),
                ('realisasidankelsisa_lpjnilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai LPJ TU')),
                ('realisasidankelsisa_sts', models.CharField(max_length=100, unique=True, verbose_name='No STS TU')),
                ('realisasidankelsisa_ststgl', models.DateField(verbose_name='Tanggal STS TU')),
                ('realisasidankelsisa_stsnilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai STS TU')),
                ('realisasidankelsisa_verif', models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0, editable=False)),
                ('realisasidankelsisa_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Sumber Dana')),
                ('realisasidankelsisa_rencana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dankel.rencdankelsisa', verbose_name='Kegiatan')),
                ('realisasidankelsisa_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd')),
                ('realisasidankelsisa_tahap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.tahapdana', verbose_name='Tahap Realisasi')),
            ],
        ),
    ]
