# Generated by Django 4.2.11 on 2024-07-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0003_alter_realisasidankel_realisasidankel_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasidankel',
            name='realisasidankel_tahun',
            field=models.IntegerField(default=2024, verbose_name='Tahun'),
        ),
    ]
