# Generated by Django 4.2.11 on 2024-06-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0004_remove_rencdankel_rencdankel_opd_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rencdankel',
            constraint=models.UniqueConstraint(fields=('rencdankel_tahun', 'rencdankel_subopd', 'rencdankel_sub'), name='unique_rencdankel'),
        ),
    ]
