# Generated by Django 4.2.11 on 2024-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0005_realisasidankel_realisasidankel_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisasidankelsisa',
            name='realisasidankelsisa_output',
            field=models.IntegerField(default=1, verbose_name='Output'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realisasidankel',
            name='realisasidankel_output',
            field=models.IntegerField(verbose_name='Output'),
        ),
    ]
