# Generated by Django 4.2.11 on 2024-06-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0005_rencdankel_unique_rencdankel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencdankel',
            name='rencdankel_verif',
            field=models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0),
        ),
        migrations.AddField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_verif',
            field=models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0),
        ),
    ]
