# Generated by Django 4.2.11 on 2024-08-07 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_alter_opd_kode_opd'),
        ('dausg', '0002_remove_dankelprog_dankel_subrinc_and_more'),
        ('dana', '0004_remove_subkegiatan_sub_dana_and_more'),
        ('dankel', '0006_realisasidankelsisa_realisasidankelsisa_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasidankel',
            name='realisasidankel_rencana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dankel.rencdankel', verbose_name='Kegiatan'),
        ),
        migrations.CreateModel(
            name='RencDankeljadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rencdankel_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('rencdankel_pagu', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Anggaran')),
                ('rencdankel_output', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Output')),
                ('rencdankel_ket', models.TextField(blank=True, verbose_name='Keterangan Kegiatan')),
                ('rencdankel_jadwal', models.IntegerField(verbose_name=models.IntegerField(choices=[(1, 'Rencana Induk'), (2, 'Rencana Perubahan')], editable=False))),
                ('rencdankel_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Sumber Dana')),
                ('rencdankel_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dausg.dankelsub', verbose_name='Sub Kegiatan')),
                ('rencdankel_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd')),
            ],
        ),
    ]
