# Generated by Django 4.2.11 on 2024-06-23 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dausg', '0009_dausgkesehatankeg_dausgpendidikankeg_dausgpukeg_and_more'),
        ('opd', '0008_alter_subopd_sub_opd'),
        ('dankel', '0006_rencdankel_rencdankel_verif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_sub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dausg.dankelsub', verbose_name='Sub Kegiatan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_subopd',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_tahun',
            field=models.IntegerField(default=2024, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencdankel',
            name='rencdankel_verif',
            field=models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_verif',
            field=models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0, editable=False),
        ),
    ]
