# Generated by Django 4.2.11 on 2024-06-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0007_rencdankelsisa_rencdankelsisa_sub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_rencana',
        ),
    ]
