# Generated by Django 4.2.11 on 2024-08-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0007_alter_realisasidankel_realisasidankel_rencana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencdankeljadwal',
            name='rencdankel_jadwal',
            field=models.IntegerField(choices=[(1, 'Rencana Induk'), (2, 'Rencana Perubahan')]),
        ),
    ]
