# Generated by Django 4.2.11 on 2024-06-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0008_subrinc_subrinc_slug'),
        ('dankel', '0008_remove_rencdankelsisa_rencdankelsisa_rencana'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencdankel',
            name='rencdankel_dana',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='dana.subrinc', verbose_name='Sumber Dana'),
            preserve_default=False,
        ),
    ]
