# Generated by Django 4.2.11 on 2024-06-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0008_subrinc_subrinc_slug'),
        ('dankel', '0009_rencdankel_rencdankel_dana'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_dana',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='dana.subrinc', verbose_name='Sumber Dana'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='rencdankelsisa',
            constraint=models.UniqueConstraint(fields=('rencdankelsisa_tahun', 'rencdankelsisa_subopd', 'rencdankelsisa_sub'), name='unique_rencdankelsisa'),
        ),
    ]
