# Generated by Django 4.2.11 on 2024-08-08 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0010_rencdankeljadwalsisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasidankel',
            name='realisasidankel_rencana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dankel.rencdankeljadwal', verbose_name='Kegiatan'),
        ),
    ]
