# Generated by Django 4.2.11 on 2024-07-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0008_subrinc_subrinc_slug'),
        ('dankel', '0011_alter_rencdankel_rencdankel_dana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencdankel',
            name='rencdankel_dana',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dana.subrinc', verbose_name='Sumber Dana'),
        ),
    ]
