# Generated by Django 4.2.11 on 2024-08-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0013_alter_realisasidankel_realisasidankel_rencana'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencdankeljadwal',
            name='rencdankel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rencdankeljadwalsisa',
            name='rencdankelsisa_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
