# Generated by Django 4.2.11 on 2024-08-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0014_rencdankeljadwal_rencdankel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisasidankel',
            name='realisasidankel_idrencana',
            field=models.IntegerField(default=3, verbose_name='Id Rencana'),
            preserve_default=False,
        ),
    ]
