# Generated by Django 4.2.11 on 2024-07-06 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0008_subrinc_subrinc_slug'),
        ('opd', '0008_alter_subopd_sub_opd'),
        ('dankel', '0014_alter_rencdankelsisa_rencdankelsisa_dana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_output',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Output Sisa'),
        ),
        migrations.AlterField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_pagu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Anggaran Sisa'),
        ),
        migrations.CreateModel(
            name='RealisasiDankel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realisasidankel_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('realisasidankel_sp2dtu', models.CharField(max_length=100, verbose_name='No SP2D TU')),
                ('realisasidankel_tgl', models.DateField(verbose_name='Tanggal SP2D TU')),
                ('realisasidankel_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai SP2D')),
                ('realisasidankel_lpj', models.CharField(max_length=100, verbose_name='No LPJ TU')),
                ('realisasidankel_lpjtgl', models.DateField(verbose_name='Tanggal LPJ TU')),
                ('realisasidankel_lpjnilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai LPJ TU')),
                ('realisasidankel_sts', models.CharField(max_length=100, verbose_name='No STS TU')),
                ('realisasidankel_ststgl', models.DateField(verbose_name='Tanggal STS TU')),
                ('realisasidankel_stsnilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai STS TU')),
                ('realisasidankel_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subrinc', verbose_name='Sumber Dana')),
                ('realisasidankel_rencana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dankel.rencdankel', verbose_name='Kegiatan')),
                ('realisasidankel_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd')),
                ('realisasidankel_tahap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.tahapdana', verbose_name='Tahap Realisasi')),
            ],
        ),
    ]
