# Generated by Django 4.2.11 on 2024-07-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0015_alter_rencdankelsisa_rencdankelsisa_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realisasidankel',
            name='realisasidankel_lpj',
        ),
        migrations.RemoveField(
            model_name='realisasidankel',
            name='realisasidankel_lpjnilai',
        ),
        migrations.RemoveField(
            model_name='realisasidankel',
            name='realisasidankel_lpjtgl',
        ),
        migrations.RemoveField(
            model_name='realisasidankel',
            name='realisasidankel_nilai',
        ),
        migrations.RemoveField(
            model_name='realisasidankel',
            name='realisasidankel_rencana',
        ),
        migrations.RemoveField(
            model_name='realisasidankel',
            name='realisasidankel_sp2dtu',
        ),
        migrations.RemoveField(
            model_name='realisasidankel',
            name='realisasidankel_sts',
        ),
        migrations.RemoveField(
            model_name='realisasidankel',
            name='realisasidankel_stsnilai',
        ),
        migrations.RemoveField(
            model_name='realisasidankel',
            name='realisasidankel_ststgl',
        ),
        migrations.RemoveField(
            model_name='realisasidankel',
            name='realisasidankel_tgl',
        ),
        migrations.CreateModel(
            name='Realdankeldetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realdankeldetail_sp2dtu', models.CharField(max_length=100, verbose_name='No SP2D TU')),
                ('realdankeldetail_tgl', models.DateField(verbose_name='Tanggal SP2D TU')),
                ('realdankeldetail_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai SP2D')),
                ('realdankeldetail_lpj', models.CharField(max_length=100, verbose_name='No LPJ TU')),
                ('realdankeldetail_lpjtgl', models.DateField(verbose_name='Tanggal LPJ TU')),
                ('realdankeldetail_lpjnilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai LPJ TU')),
                ('realdankeldetail_sts', models.CharField(max_length=100, verbose_name='No STS TU')),
                ('realdankeldetail_ststgl', models.DateField(verbose_name='Tanggal STS TU')),
                ('realdankeldetail_stsnilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai STS TU')),
                ('realdankeldetail_rencana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dankel.rencdankel', verbose_name='Kegiatan')),
                ('realdankeldetail_tahap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dankel.realisasidankel', verbose_name='Tahap Pencairan')),
            ],
        ),
    ]
