# Generated by Django 4.2.11 on 2024-07-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0016_remove_realisasidankel_realisasidankel_lpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisasidankel',
            name='realisasidankel_valid',
            field=models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0, editable=False),
        ),
    ]
