# Generated by Django 4.2.11 on 2024-08-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0016_realisasidankelsisa_realisasidankelsisa_idrencana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasidankel',
            name='realisasidankel_verif',
            field=models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0),
        ),
    ]
