# Generated by Django 4.2.11 on 2024-08-31 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0017_alter_realisasidankel_realisasidankel_verif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasidankel',
            name='realisasidankel_verif',
            field=models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='rencdankeljadwal',
            name='rencdankel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dankel.rencdankel', verbose_name='Id Rencana'),
        ),
    ]
