# Generated by Django 4.2.11 on 2024-07-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0017_realisasidankel_realisasidankel_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realisasidankel',
            old_name='realisasidankel_valid',
            new_name='realisasidankel_verif',
        ),
        migrations.AddField(
            model_name='realdankeldetail',
            name='realdankeldetail_verif',
            field=models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0, editable=False),
        ),
    ]
