# Generated by Django 4.2.11 on 2024-08-31 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0018_alter_realisasidankel_realisasidankel_verif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasidankel',
            name='realisasidankel_idrencana',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dankel.rencdankel', verbose_name='Id Rencana'),
        ),
    ]
