# Generated by Django 4.2.11 on 2024-09-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0020_alter_realisasidankelsisa_realisasidankelsisa_idrencana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencdankeljadwal',
            name='rencdankel_jadwal',
            field=models.IntegerField(choices=[(1, 'Rencana Induk'), (2, 'Rencana Perubahan')], null=True, verbose_name='Posting Jadwal'),
        ),
        migrations.AlterField(
            model_name='rencdankeljadwalsisa',
            name='rencdankelsisa_jadwal',
            field=models.IntegerField(choices=[(1, 'Rencana Induk'), (2, 'Rencana Perubahan')], null=True, verbose_name='Posting Jadwal'),
        ),
    ]
