# Generated by Django 4.2.11 on 2026-01-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dankel', '0023_alter_rencdankeljadwal_rencdankel_jadwal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasidankel',
            name='realisasidankel_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='realisasidankelsisa',
            name='realisasidankelsisa_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencdankel',
            name='rencdankel_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencdankeljadwal',
            name='rencdankel_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencdankeljadwalsisa',
            name='rencdankelsisa_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencdankelsisa',
            name='rencdankelsisa_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
    ]
