# Generated by Django 4.2.11 on 2024-05-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_opd', models.CharField(max_length=10)),
                ('nama_opd', models.CharField(max_length=100)),
            ],
        ),
    ]
