# Generated by Django 4.2.11 on 2024-05-27 12:07

import django.core.validators
from django.db import migrations, models
import functools
import project.validations


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_author_publisher_alter_opd_kode_opd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd',
            name='kode_opd',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Data yang diinput harus berupa angka', regex='^[0-9]+$'), functools.partial(project.validations.unik, *(), **{'app_name': 'opd', 'field': 'kode_opd', 'model_name': 'Opd'})]),
        ),
        migrations.AlterField(
            model_name='opd',
            name='nama_opd',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Data yang diinput minimal 2 karakter'), functools.partial(project.validations.unik, *(), **{'app_name': 'opd', 'field': 'nama_opd', 'model_name': 'Opd'})]),
        ),
    ]
