# Generated by Django 4.2.11 on 2024-07-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_alter_opd_kode_opd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd',
            name='kode_opd',
            field=models.CharField(error_messages={'unique': 'Data, nilai ini sudah ada dalam database.'}, max_length=25, unique=True, verbose_name='Kode OPD'),
        ),
    ]
