# Generated by Django 4.2.11 on 2024-05-29 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_alter_opd_kode_opd_alter_opd_nama_opd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd',
            name='kode_opd',
            field=models.CharField(error_messages={'unique': 'Maaf, nilai ini sudah ada dalam database.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Data yang diinput harus berupa angka', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='opd',
            name='nama_opd',
            field=models.CharField(error_messages={'unique': 'Maaf, nilai ini sudah ada dalam database.'}, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Data yang diinput minimal 2 karakter')]),
        ),
    ]
