# Generated by Django 4.2.11 on 2024-08-16 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_alter_opd_kode_opd'),
    ]

    operations = [
        migrations.CreateModel(
            name='pejabat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pejabat_jabatan', models.CharField(max_length=40, verbose_name='Jabatan')),
                ('pejabat_nama', models.CharField(max_length=40, verbose_name='Nama Pejabat')),
                ('pejabat_nip', models.CharField(error_messages='NIP sudah ada', max_length=18, unique=True, verbose_name='NIP')),
                ('pejabat_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Nama OPD')),
            ],
        ),
    ]
