# Generated by Django 4.2.11 on 2024-08-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0004_pejabat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pejabat',
            name='pejabat_sub',
            field=models.ForeignKey(error_messages='OPD ini sudah memiliki Pejabat', on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', unique=True, verbose_name='Nama OPD'),
        ),
    ]
