# Generated by Django 4.2.11 on 2024-06-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0006_alter_opd_kode_opd_alter_opd_nama_opd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOpd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_nama', models.CharField(max_length=200, verbose_name='Nama Sub Opd')),
                ('sub_opd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.opd', verbose_name='Opd')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
