# Generated by Django 4.2.11 on 2024-06-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0007_subopd_remove_book_author_remove_book_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subopd',
            name='sub_opd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.opd', verbose_name='Sub Opd'),
        ),
    ]
