# Generated by Django 4.2.11 on 2024-09-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0005_alter_kegiatan_kegiatan_slug_and_more'),
        ('opd', '0007_pejabat_pejabat_foto_pejabat_pejabat_lokasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdDana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opddana_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Dana')),
                ('opddana_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='OPD Pengelola')),
            ],
        ),
    ]
