# Generated by Django 4.2.11 on 2024-09-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0008_opddana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pejabat',
            name='pejabat_foto',
            field=models.ImageField(blank=True, null=True, upload_to='kop_fotos/', verbose_name='Foto KOP Surat'),
        ),
    ]
