# Generated by Django 4.2.11 on 2026-01-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0009_alter_pejabat_pejabat_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='subopd',
            name='sub_opd_kode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kode Sub Opd'),
        ),
    ]
