# Generated by Django 4.2.11 on 2026-01-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0010_subopd_sub_opd_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subopd',
            name='sub_opd_kode',
            field=models.CharField(error_messages='Kode Sub Opd sudah ada', max_length=50, unique=True, verbose_name='Kode Sub Opd'),
        ),
    ]
