# Generated by Django 4.2.11 on 2024-09-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0008_opddana'),
        ('dausg', '0006_alter_dankelsub_dankelsub_nama'),
        ('dana', '0005_alter_kegiatan_kegiatan_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rencanaposting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rencana_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('rencana_pagu', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Anggaran')),
                ('rencana_output', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Output')),
                ('rencana_ket', models.TextField(blank=True, verbose_name='Keterangan Kegiatan')),
                ('rencana_verif', models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0, editable=False)),
                ('rencana_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Sumber Dana')),
                ('rencana_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dausg.dausgpendidikansub', verbose_name='Sub Kegiatan')),
                ('rencana_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd')),
            ],
        ),
        migrations.CreateModel(
            name='Rencana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rencana_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('rencana_pagu', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Anggaran')),
                ('rencana_output', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Output')),
                ('rencana_ket', models.TextField(blank=True, verbose_name='Keterangan Kegiatan')),
                ('rencana_verif', models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui'), (2, 'Ditolak')], default=0, editable=False)),
                ('rencana_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Sumber Dana')),
                ('rencana_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dausg.dausgpendidikansub', verbose_name='Sub Kegiatan')),
                ('rencana_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rencana',
            constraint=models.UniqueConstraint(fields=('rencana_tahun', 'rencana_subopd', 'rencana_sub'), name='unique_rencana'),
        ),
    ]
