# Generated by Django 4.2.11 on 2024-09-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rencana',
            name='unique_rencana',
        ),
        migrations.RenameField(
            model_name='rencana',
            old_name='rencana_sub',
            new_name='rencana_kegiatan',
        ),
        migrations.RenameField(
            model_name='rencanaposting',
            old_name='rencana_sub',
            new_name='rencana_kegiatan',
        ),
        migrations.RemoveField(
            model_name='rencanaposting',
            name='rencana_verif',
        ),
        migrations.AddField(
            model_name='rencanaposting',
            name='rencana_jadwal',
            field=models.IntegerField(choices=[(1, 'Rencana Induk'), (2, 'Rencana Perubahan')], null=True, verbose_name='Posting Jadwal'),
        ),
        migrations.AddField(
            model_name='rencanaposting',
            name='rencdankel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pendidikan.rencana', verbose_name='Id Rencana'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rencana',
            name='rencana_ket',
            field=models.TextField(verbose_name='Kode Sub Kegiatan DPA'),
        ),
        migrations.AlterField(
            model_name='rencanaposting',
            name='rencana_ket',
            field=models.TextField(verbose_name='Kode Sub Kegiatan DPA'),
        ),
        migrations.AddConstraint(
            model_name='rencana',
            constraint=models.UniqueConstraint(fields=('rencana_tahun', 'rencana_subopd', 'rencana_kegiatan'), name='unique_rencana'),
        ),
    ]
