# Generated by Django 4.2.11 on 2024-09-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0002_remove_rencana_unique_rencana_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rencanaposting',
            old_name='rencdankel_id',
            new_name='rencana_id',
        ),
    ]
