# Generated by Django 4.2.11 on 2024-09-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0003_rename_rencdankel_id_rencanaposting_rencana_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencana',
            name='rencana_ket',
            field=models.TextField(max_length=17, verbose_name='Kode Sub Kegiatan DPA'),
        ),
    ]
