# Generated by Django 4.2.11 on 2024-09-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0004_alter_rencana_rencana_ket'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencana',
            name='rencana_pagudpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai Pagu Sub Kegiatan sesuai DPA'),
        ),
        migrations.AlterField(
            model_name='rencana',
            name='rencana_ket',
            field=models.TextField(max_length=17, verbose_name='Kode Sub Kegiatan DPA *) cth :  1.01.01.2.01.0001 '),
        ),
        migrations.AlterField(
            model_name='rencana',
            name='rencana_pagu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Kegiatan DAU SG'),
        ),
    ]
