# Generated by Django 4.2.11 on 2024-09-13 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dausg', '0006_alter_dankelsub_dankelsub_nama'),
        ('pendidikan', '0005_rencana_rencana_pagudpa_alter_rencana_rencana_ket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanaposting',
            name='rencana_pagudpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai Pagu Sub Kegiatan sesuai DPA'),
        ),
        migrations.AlterField(
            model_name='rencana',
            name='rencana_kegiatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dausg.dausgpendidikansub', verbose_name='Sub Kegiatan DAU SG'),
        ),
        migrations.AlterField(
            model_name='rencana',
            name='rencana_verif',
            field=models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='rencanaposting',
            name='rencana_kegiatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dausg.dausgpendidikansub', verbose_name='Sub Kegiatan DAU SG'),
        ),
        migrations.AlterField(
            model_name='rencanaposting',
            name='rencana_ket',
            field=models.TextField(max_length=17, verbose_name='Kode Sub Kegiatan DPA *) cth :  1.01.01.2.01.0001 '),
        ),
        migrations.AlterField(
            model_name='rencanaposting',
            name='rencana_pagu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Kegiatan DAU SG'),
        ),
    ]
