# Generated by Django 4.2.11 on 2024-09-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0006_rencanaposting_rencana_pagudpa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rencanaposting',
            old_name='rencana_dana',
            new_name='posting_dana',
        ),
        migrations.RenameField(
            model_name='rencanaposting',
            old_name='rencana_jadwal',
            new_name='posting_jadwal',
        ),
        migrations.RenameField(
            model_name='rencanaposting',
            old_name='rencana_ket',
            new_name='posting_ket',
        ),
        migrations.RenameField(
            model_name='rencanaposting',
            old_name='rencana_output',
            new_name='posting_output',
        ),
        migrations.RenameField(
            model_name='rencanaposting',
            old_name='rencana_pagu',
            new_name='posting_pagu',
        ),
        migrations.RenameField(
            model_name='rencanaposting',
            old_name='rencana_pagudpa',
            new_name='posting_pagudpa',
        ),
        migrations.RenameField(
            model_name='rencanaposting',
            old_name='rencana_id',
            new_name='posting_rencanaid',
        ),
        migrations.RenameField(
            model_name='rencanaposting',
            old_name='rencana_kegiatan',
            new_name='posting_subkegiatan',
        ),
        migrations.RenameField(
            model_name='rencanaposting',
            old_name='rencana_subopd',
            new_name='posting_subopd',
        ),
        migrations.RenameField(
            model_name='rencanaposting',
            old_name='rencana_tahun',
            new_name='posting_tahun',
        ),
    ]
