# Generated by Django 4.2.11 on 2024-09-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0008_opddana'),
        ('dana', '0005_alter_kegiatan_kegiatan_slug_and_more'),
        ('dausg', '0006_alter_dankelsub_dankelsub_nama'),
        ('pendidikan', '0007_rename_rencana_dana_rencanaposting_posting_dana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realisasi_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('realisasi_output', models.IntegerField(verbose_name='Output')),
                ('realisasi_sp2d', models.CharField(max_length=100, unique=True, verbose_name='No SP2D TU')),
                ('realisasi_tgl', models.DateField(verbose_name='Tanggal SP2D TU')),
                ('realisasi_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai SP2D')),
                ('realisasi_verif', models.IntegerField(choices=[(0, 'Input Dinas'), (1, 'Disetujui')], default=0, editable=False)),
                ('realisasi_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Sumber Dana')),
                ('realisasi_kegiatan', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dausg.dausgpendidikansub', verbose_name='Sub Kegiatan DAU SG')),
                ('realisasi_rencana', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='pendidikan.rencana', verbose_name='Id Rencana')),
                ('realisasi_rencanaposting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendidikan.rencanaposting', verbose_name='Kegiatan')),
                ('realisasi_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd')),
                ('realisasi_tahap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.tahapdana', verbose_name='Tahap Realisasi')),
            ],
        ),
    ]
