# Generated by Django 4.2.11 on 2024-09-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0008_realisasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realisasi',
            old_name='realisasi_kegiatan',
            new_name='realisasi_subkegiatan',
        ),
        migrations.AlterField(
            model_name='realisasi',
            name='realisasi_output',
            field=models.IntegerField(verbose_name='Capaian Output'),
        ),
        migrations.AlterField(
            model_name='realisasi',
            name='realisasi_sp2d',
            field=models.CharField(max_length=100, unique=True, verbose_name='No SP2D'),
        ),
        migrations.AlterField(
            model_name='realisasi',
            name='realisasi_tgl',
            field=models.DateField(verbose_name='Tanggal SP2D'),
        ),
    ]
