# Generated by Django 4.2.11 on 2024-09-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0009_rename_realisasi_kegiatan_realisasi_realisasi_subkegiatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasi',
            name='realisasi_verif',
            field=models.IntegerField(choices=[(0, 'Diinput Dinas'), (1, 'Disetujui APIP')], default=0, editable=False, verbose_name='Verifikasi'),
        ),
        migrations.AlterField(
            model_name='rencana',
            name='rencana_ket',
            field=models.TextField(max_length=17, verbose_name='Kode Sub Kegiatan DPA *) contoh :  1.01.01.2.01.0001 '),
        ),
        migrations.AlterField(
            model_name='rencanaposting',
            name='posting_ket',
            field=models.TextField(max_length=17, verbose_name='Kode Sub Kegiatan DPA *) contoh :  1.01.01.2.01.0001 '),
        ),
    ]
