# Generated by Django 4.2.11 on 2024-11-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0011_rencanasisa_rencanapostingsisa_realisasisisa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencana',
            name='rencana_ket',
            field=models.TextField(max_length=17, verbose_name='Kode Sub Kegiatan DPA *) contoh: 1.01.01.2.01.0001'),
        ),
        migrations.AlterModelTable(
            name='rencana',
            table='rencana',
        ),
    ]
