# Generated by Django 4.2.11 on 2024-11-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0012_alter_rencana_rencana_ket_alter_rencana_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rencanapostingsisa',
            name='posting_dana',
        ),
        migrations.RemoveField(
            model_name='rencanapostingsisa',
            name='posting_rencanaid',
        ),
        migrations.RemoveField(
            model_name='rencanapostingsisa',
            name='posting_subkegiatan',
        ),
        migrations.RemoveField(
            model_name='rencanapostingsisa',
            name='posting_subopd',
        ),
        migrations.AlterField(
            model_name='rencanasisa',
            name='rencana_ket',
            field=models.TextField(max_length=17, verbose_name='Kode Sub Kegiatan DPA *) contoh: 1.01.01.2.01.0001'),
        ),
        migrations.AlterModelTable(
            name='rencana',
            table='rencana_pendidikan',
        ),
        migrations.AlterModelTable(
            name='rencanasisa',
            table='rencanasisa_pendidikan',
        ),
        migrations.DeleteModel(
            name='Realisasisisa',
        ),
        migrations.DeleteModel(
            name='Rencanapostingsisa',
        ),
    ]
