# Generated by Django 4.2.11 on 2024-11-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0013_remove_rencanapostingsisa_posting_dana_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rencana',
            table='pendidikan_rencana',
        ),
        migrations.AlterModelTable(
            name='rencanasisa',
            table='pendidikan_rencanasisa',
        ),
    ]
