# Generated by Django 4.2.11 on 2024-11-08 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0009_alter_pejabat_pejabat_foto'),
        ('dausg', '0006_alter_dankelsub_dankelsub_nama'),
        ('dana', '0005_alter_kegiatan_kegiatan_slug_and_more'),
        ('pendidikan', '0014_alter_rencana_table_alter_rencanasisa_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rencanaposting',
            table='pendidikan_rencanaposting',
        ),
        migrations.CreateModel(
            name='Rencanapostingsisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('posting_pagu', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Pagu Kegiatan DAU SG')),
                ('posting_output', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Output')),
                ('posting_ket', models.TextField(max_length=17, verbose_name='Kode Sub Kegiatan DPA *) contoh :  1.01.01.2.01.0001 ')),
                ('posting_pagudpa', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai Pagu Sub Kegiatan sesuai DPA')),
                ('posting_jadwal', models.IntegerField(choices=[(1, 'Rencana Induk'), (2, 'Rencana Perubahan')], null=True, verbose_name='Posting Jadwal')),
                ('posting_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Sumber Dana')),
                ('posting_rencanaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendidikan.rencana', verbose_name='Id Rencana')),
                ('posting_subkegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dausg.dausgpendidikansub', verbose_name='Sub Kegiatan DAU SG')),
                ('posting_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd')),
            ],
            options={
                'db_table': 'pendidikan_rencanapostingsisa',
                'abstract': False,
            },
        ),
    ]
