# Generated by Django 4.2.11 on 2024-11-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0005_alter_kegiatan_kegiatan_slug_and_more'),
        ('opd', '0009_alter_pejabat_pejabat_foto'),
        ('dausg', '0006_alter_dankelsub_dankelsub_nama'),
        ('pendidikan', '0016_alter_rencanapostingsisa_posting_rencanaid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='realisasi',
            table='pendidikan_realisasi',
        ),
        migrations.CreateModel(
            name='Realisasisisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realisasi_tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('realisasi_output', models.IntegerField(verbose_name='Capaian Output')),
                ('realisasi_sp2d', models.CharField(max_length=100, unique=True, verbose_name='No SP2D')),
                ('realisasi_tgl', models.DateField(verbose_name='Tanggal SP2D')),
                ('realisasi_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Nilai SP2D')),
                ('realisasi_verif', models.IntegerField(choices=[(0, 'Diinput Dinas'), (1, 'Disetujui APIP')], default=0, editable=False, verbose_name='Verifikasi')),
                ('realisasi_dana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.subkegiatan', verbose_name='Sumber Dana')),
                ('realisasi_rencana', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='pendidikan.rencanasisa', verbose_name='Id Rencana')),
                ('realisasi_rencanaposting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendidikan.rencanapostingsisa', verbose_name='Kegiatan')),
                ('realisasi_subkegiatan', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dausg.dausgpendidikansub', verbose_name='Sub Kegiatan DAU SG')),
                ('realisasi_subopd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.subopd', verbose_name='Sub Opd')),
                ('realisasi_tahap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.tahapdana', verbose_name='Tahap Realisasi')),
            ],
            options={
                'db_table': 'pendidikan_realisasisisa',
                'abstract': False,
            },
        ),
    ]
