# Generated by Django 4.2.11 on 2025-01-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0017_alter_realisasi_table_realisasisisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasi',
            name='realisasi_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='realisasisisa',
            name='realisasi_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencana',
            name='rencana_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanaposting',
            name='posting_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanapostingsisa',
            name='posting_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanasisa',
            name='rencana_tahun',
            field=models.IntegerField(default=2025, verbose_name='Tahun'),
        ),
    ]
