# Generated by Django 4.2.11 on 2025-02-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0001_initial'),
        ('pendidikan', '0018_alter_realisasi_realisasi_tahun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanaposting',
            name='posting_jadwal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jadwal.jadwal', verbose_name='Posting Jadwal'),
        ),
        migrations.AlterField(
            model_name='rencanapostingsisa',
            name='posting_jadwal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jadwal.jadwal', verbose_name='Posting Jadwal'),
        ),
    ]
