# Generated by Django 4.2.11 on 2026-01-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0019_alter_rencanaposting_posting_jadwal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasi',
            name='realisasi_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='realisasisisa',
            name='realisasi_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencana',
            name='rencana_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanaposting',
            name='posting_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanapostingsisa',
            name='posting_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='rencanasisa',
            name='rencana_tahun',
            field=models.IntegerField(default=2026, verbose_name='Tahun'),
        ),
    ]
