# Generated by Django 6.0.1 on 2026-02-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0020_alter_realisasi_realisasi_tahun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisasi',
            name='realisasi_sp2d',
            field=models.CharField(max_length=100, verbose_name='No SP2D'),
        ),
        migrations.AlterField(
            model_name='realisasisisa',
            name='realisasi_sp2d',
            field=models.CharField(max_length=100, verbose_name='No SP2D'),
        ),
    ]
